-- Flat Trash Phase 2 - Supabase schema
-- IMPORTANT SETUP ORDER:
-- 1. Create the three Auth users first in Supabase Authentication:
--      theodoros@flat-trash.invalid
--      prionto@flat-trash.invalid
--      camila@flat-trash.invalid
-- 2. Then run this script in the Supabase SQL Editor.

begin;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (username = lower(username)),
  display_name text not null,
  role text not null default 'member' check (role in ('admin','member')),
  availability text not null default 'home' check (availability in ('home','away')),
  away_until date,
  rotation_position integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.trash_types (
  id text primary key,
  name text not null,
  emoji text not null,
  sort_order integer unique not null,
  status text not null default 'ok' check (status in ('ok','getting_full','needs_taking')),
  next_person uuid references public.profiles(id),
  last_taken_by uuid references public.profiles(id),
  last_taken_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  type text not null check (type in ('taken','status','vacation','password_reset','admin')),
  actor_id uuid references public.profiles(id),
  trash_id text references public.trash_types(id),
  expected_person_id uuid references public.profiles(id),
  actual_person_id uuid references public.profiles(id),
  target_person_id uuid references public.profiles(id),
  voluntary boolean,
  from_status text,
  to_status text,
  summary text not null
);

-- Seed profiles by matching the synthetic Auth email addresses.
insert into public.profiles (id, username, display_name, role, rotation_position)
select id, 'theodoros', 'Theodoros', 'admin', 1
from auth.users where lower(email) = 'theodoros@flat-trash.invalid'
on conflict (id) do update set
  username = excluded.username,
  display_name = excluded.display_name,
  role = 'admin',
  rotation_position = 1;

insert into public.profiles (id, username, display_name, role, rotation_position)
select id, 'prionto', 'Prionto', 'member', 2
from auth.users where lower(email) = 'prionto@flat-trash.invalid'
on conflict (id) do update set
  username = excluded.username,
  display_name = excluded.display_name,
  role = 'member',
  rotation_position = 2;

insert into public.profiles (id, username, display_name, role, rotation_position)
select id, 'camila', 'Camila', 'member', 3
from auth.users where lower(email) = 'camila@flat-trash.invalid'
on conflict (id) do update set
  username = excluded.username,
  display_name = excluded.display_name,
  role = 'member',
  rotation_position = 3;

do $$
begin
  if (select count(*) from public.profiles) < 3 then
    raise exception 'Expected 3 profiles. Create the three Auth users first, then run schema.sql again.';
  end if;
end $$;

insert into public.trash_types (id, name, emoji, sort_order, next_person)
values
  ('organics', 'Organics & Others', '🗑️', 1, (select id from public.profiles where username='theodoros')),
  ('paper', 'Paper & Cardboard', '📦', 2, (select id from public.profiles where username='theodoros')),
  ('metal', 'Metal', '🥫', 3, (select id from public.profiles where username='theodoros')),
  ('plastic', 'Plastic', '♻️', 4, (select id from public.profiles where username='theodoros')),
  ('bathroom', 'Bathroom / Toilet', '🚽', 5, (select id from public.profiles where username='theodoros')),
  ('glass', 'Glass', '🍾', 6, (select id from public.profiles where username='theodoros'))
on conflict (id) do update set
  name = excluded.name,
  emoji = excluded.emoji,
  sort_order = excluded.sort_order;

-- Helper: effective availability.
create or replace function public.person_is_available(p_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select
        availability = 'home'
        or (availability = 'away' and away_until is not null and away_until < current_date)
      from public.profiles
      where id = p_id
    ),
    false
  );
$$;

create or replace function public.current_user_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

-- Helper: next available person after the person who actually completed the task.
create or replace function public.next_available_after(p_person uuid)
returns uuid
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_pos integer;
  v_next uuid;
begin
  select rotation_position into v_pos
  from public.profiles where id = p_person;

  select id into v_next
  from public.profiles
  where rotation_position > v_pos
    and public.person_is_available(id)
  order by rotation_position
  limit 1;

  if v_next is null then
    select id into v_next
    from public.profiles
    where public.person_is_available(id)
    order by rotation_position
    limit 1;
  end if;

  return v_next;
end;
$$;

-- Anyone signed in can mark a trash status.
create or replace function public.set_trash_status(
  p_trash_id text,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_old text;
  v_trash_name text;
  v_actor_name text;
begin
  if v_actor is null then
    raise exception 'Not authenticated';
  end if;

  if p_status not in ('ok','getting_full','needs_taking') then
    raise exception 'Invalid status';
  end if;

  select status, name into v_old, v_trash_name
  from public.trash_types
  where id = p_trash_id
  for update;

  if not found then
    raise exception 'Unknown trash type';
  end if;

  if v_old = p_status then
    return;
  end if;

  select display_name into v_actor_name
  from public.profiles where id = v_actor;

  update public.trash_types
  set status = p_status, updated_at = now()
  where id = p_trash_id;

  insert into public.activity_log (
    type, actor_id, trash_id, from_status, to_status, summary
  )
  values (
    'status',
    v_actor,
    p_trash_id,
    v_old,
    p_status,
    v_actor_name || ' changed ' || v_trash_name || ' from ' ||
      case v_old
        when 'ok' then 'OK'
        when 'getting_full' then 'Getting full'
        when 'needs_taking' then 'Needs taking'
      end ||
      ' to ' ||
      case p_status
        when 'ok' then 'OK'
        when 'getting_full' then 'Getting full'
        when 'needs_taking' then 'Needs taking'
      end
  );
end;
$$;

-- Record a completed trash action.
-- If someone takes another person's turn, voluntary=true is stored.
-- Rotation continues after the ACTUAL person who completed it.
create or replace function public.take_out_trash(p_trash_id text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_expected uuid;
  v_next uuid;
  v_trash_name text;
  v_actor_name text;
  v_expected_name text;
  v_voluntary boolean;
begin
  if v_actor is null then
    raise exception 'Not authenticated';
  end if;

  select next_person, name into v_expected, v_trash_name
  from public.trash_types
  where id = p_trash_id
  for update;

  if not found then
    raise exception 'Unknown trash type';
  end if;

  select display_name into v_actor_name from public.profiles where id = v_actor;
  select display_name into v_expected_name from public.profiles where id = v_expected;

  v_voluntary := (v_expected is distinct from v_actor);
  v_next := public.next_available_after(v_actor);

  update public.trash_types
  set
    status = 'ok',
    last_taken_by = v_actor,
    last_taken_at = now(),
    next_person = v_next,
    updated_at = now()
  where id = p_trash_id;

  insert into public.activity_log (
    type, actor_id, trash_id, expected_person_id, actual_person_id, voluntary, summary
  )
  values (
    'taken',
    v_actor,
    p_trash_id,
    v_expected,
    v_actor,
    v_voluntary,
    case
      when v_voluntary then
        v_actor_name || ' voluntarily took out ' || v_trash_name ||
        ' (it was ' || coalesce(v_expected_name, 'someone else') || '''s turn)'
      else
        v_actor_name || ' took out ' || v_trash_name
    end
  );
end;
$$;

-- Change availability. A member may change their own; admin may change anyone.
-- If a member goes away while assigned to a trash type, those pending turns are skipped.
create or replace function public.set_availability(
  p_target_person uuid,
  p_availability text,
  p_away_until date default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_name text;
  v_target_name text;
  r record;
  v_replacement uuid;
begin
  if v_actor is null then
    raise exception 'Not authenticated';
  end if;

  if p_target_person <> v_actor and not public.current_user_is_admin() then
    raise exception 'Not authorized';
  end if;

  if p_availability not in ('home','away') then
    raise exception 'Invalid availability';
  end if;

  select display_name into v_actor_name from public.profiles where id = v_actor;
  select display_name into v_target_name from public.profiles where id = p_target_person;

  update public.profiles
  set
    availability = p_availability,
    away_until = case when p_availability = 'away' then p_away_until else null end
  where id = p_target_person;

  if p_availability = 'away' then
    v_replacement := public.next_available_after(p_target_person);
    if v_replacement is not null and v_replacement <> p_target_person then
      update public.trash_types
      set next_person = v_replacement, updated_at = now()
      where next_person = p_target_person;
    end if;
  end if;

  insert into public.activity_log (
    type, actor_id, target_person_id, summary
  )
  values (
    'vacation',
    v_actor,
    p_target_person,
    v_actor_name || ' set ' || v_target_name || ' to ' ||
    case
      when p_availability = 'home' then 'Home'
      when p_away_until is null then 'Away'
      else 'Away until ' || p_away_until::text
    end
  );
end;
$$;

-- Row Level Security: clients can READ shared household state.
-- Mutations are done through the controlled SECURITY DEFINER functions above.
alter table public.profiles enable row level security;
alter table public.trash_types enable row level security;
alter table public.activity_log enable row level security;

drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read trash" on public.trash_types;
create policy "Authenticated users can read trash"
on public.trash_types for select
to authenticated
using (true);

drop policy if exists "Authenticated users can read history" on public.activity_log;
create policy "Authenticated users can read history"
on public.activity_log for select
to authenticated
using (true);

revoke all on public.profiles from anon, authenticated;
revoke all on public.trash_types from anon, authenticated;
revoke all on public.activity_log from anon, authenticated;

grant select on public.profiles to authenticated;
grant select on public.trash_types to authenticated;
grant select on public.activity_log to authenticated;

grant execute on function public.set_trash_status(text,text) to authenticated;
grant execute on function public.take_out_trash(text) to authenticated;
grant execute on function public.set_availability(uuid,text,date) to authenticated;

-- Realtime publication.
do $$
begin
  alter publication supabase_realtime add table public.profiles;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.trash_types;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.activity_log;
exception when duplicate_object then null;
end $$;

commit;
