begin;

-- =========================================================
-- 1. Notification records
-- =========================================================

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null
    references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null,
  trash_id text
    references public.trash_types(id) on delete set null,
  actor_id uuid
    references public.profiles(id) on delete set null,
  target_person_id uuid
    references public.profiles(id) on delete set null,
  url text not null default '/',
  read_at timestamptz,
  push_processed_at timestamptz,
  push_attempts integer not null default 0,
  last_push_error text,
  created_at timestamptz not null default now()
);

create index if not exists notifications_recipient_created_idx
  on public.notifications (recipient_id, created_at desc);

create index if not exists notifications_unread_idx
  on public.notifications (recipient_id, created_at desc)
  where read_at is null;

create index if not exists notifications_pending_push_idx
  on public.notifications (created_at)
  where push_processed_at is null;


-- =========================================================
-- 2. Web Push subscriptions
-- =========================================================

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null
    references public.profiles(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_idx
  on public.push_subscriptions (user_id);


-- =========================================================
-- 3. Row Level Security
-- =========================================================

alter table public.notifications enable row level security;
alter table public.push_subscriptions enable row level security;

drop policy if exists "Members can read their notifications"
  on public.notifications;

create policy "Members can read their notifications"
  on public.notifications
  for select
  to authenticated
  using (recipient_id = auth.uid());

drop policy if exists "Members can read their push subscriptions"
  on public.push_subscriptions;

create policy "Members can read their push subscriptions"
  on public.push_subscriptions
  for select
  to authenticated
  using (user_id = auth.uid());

revoke all on table public.notifications from anon, authenticated;
revoke all on table public.push_subscriptions from anon, authenticated;

grant select on table public.notifications to authenticated;
grant select on table public.push_subscriptions to authenticated;


-- =========================================================
-- 4. Register a device for Web Push
-- =========================================================

create or replace function public.register_push_subscription(
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_user_agent text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'You must be signed in.';
  end if;

  if nullif(trim(p_endpoint), '') is null
     or nullif(trim(p_p256dh), '') is null
     or nullif(trim(p_auth), '') is null then
    raise exception 'The push subscription is incomplete.';
  end if;

  insert into public.push_subscriptions (
    user_id,
    endpoint,
    p256dh,
    auth,
    user_agent,
    updated_at
  )
  values (
    v_user_id,
    p_endpoint,
    p_p256dh,
    p_auth,
    p_user_agent,
    now()
  )
  on conflict (endpoint)
  do update set
    user_id = excluded.user_id,
    p256dh = excluded.p256dh,
    auth = excluded.auth,
    user_agent = excluded.user_agent,
    updated_at = now();
end;
$$;


-- =========================================================
-- 5. Unregister a device
-- =========================================================

create or replace function public.unregister_push_subscription(
  p_endpoint text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'You must be signed in.';
  end if;

  delete from public.push_subscriptions
  where user_id = v_user_id
    and endpoint = p_endpoint;
end;
$$;


-- =========================================================
-- 6. Mark one notification as read
-- =========================================================

create or replace function public.mark_notification_read(
  p_notification_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'You must be signed in.';
  end if;

  update public.notifications
  set read_at = coalesce(read_at, now())
  where id = p_notification_id
    and recipient_id = v_user_id;
end;
$$;


-- =========================================================
-- 7. Mark all notifications as read
-- =========================================================

create or replace function public.mark_all_notifications_read()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'You must be signed in.';
  end if;

  update public.notifications
  set read_at = now()
  where recipient_id = v_user_id
    and read_at is null;
end;
$$;


-- =========================================================
-- 8. Update trash status and create an alert
-- =========================================================

create or replace function public.set_trash_status(
  p_trash_id text,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_name text;
  v_old_status text;
  v_trash_name text;
  v_assignee uuid;
begin
  if v_actor is null then
    raise exception 'You must be signed in.';
  end if;

  if p_status not in ('ok', 'getting_full', 'needs_taking') then
    raise exception 'Invalid trash status.';
  end if;

  select
    status,
    name,
    next_person
  into
    v_old_status,
    v_trash_name,
    v_assignee
  from public.trash_types
  where id = p_trash_id
  for update;

  if not found then
    raise exception 'Trash category not found.';
  end if;

  if v_old_status = p_status then
    return;
  end if;

  select display_name
  into v_actor_name
  from public.profiles
  where id = v_actor;

  update public.trash_types
  set
    status = p_status,
    updated_at = now()
  where id = p_trash_id;

  insert into public.activity_log (
    type,
    actor_id,
    trash_id,
    from_status,
    to_status,
    summary
  )
  values (
    'status',
    v_actor,
    p_trash_id,
    v_old_status,
    p_status,
    coalesce(v_actor_name, 'Someone')
      || ' changed '
      || v_trash_name
      || ' from '
      || replace(v_old_status, '_', ' ')
      || ' to '
      || replace(p_status, '_', ' ')
  );

  if p_status = 'needs_taking'
     and v_assignee is not null then
    insert into public.notifications (
      recipient_id,
      type,
      title,
      body,
      trash_id,
      actor_id,
      target_person_id,
      url
    )
    values (
      v_assignee,
      'trash_needs_taking',
      '🗑️ ' || v_trash_name || ' needs taking',
      'It is your turn to take out ' || v_trash_name || '.',
      p_trash_id,
      v_actor,
      v_assignee,
      '/'
    );
  end if;
end;
$$;


-- =========================================================
-- 9. Availability changes and reassignment notifications
-- =========================================================

create or replace function public.set_availability(
  p_target_person uuid,
  p_availability text,
  p_away_until date default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_name text;
  v_target_name text;
  v_actor_role text;
  v_replacement uuid;
  r record;
begin
  if v_actor is null then
    raise exception 'You must be signed in.';
  end if;

  if p_availability not in ('home', 'away') then
    raise exception 'Invalid availability value.';
  end if;

  select role, display_name
  into v_actor_role, v_actor_name
  from public.profiles
  where id = v_actor;

  if v_actor <> p_target_person
     and v_actor_role <> 'admin' then
    raise exception 'Only an administrator can change another member.';
  end if;

  select display_name
  into v_target_name
  from public.profiles
  where id = p_target_person;

  if not found then
    raise exception 'Member not found.';
  end if;

  update public.profiles
  set
    availability = p_availability,
    away_until = case
      when p_availability = 'away' then p_away_until
      else null
    end
  where id = p_target_person;

  if p_availability = 'away' then
    v_replacement :=
      public.next_available_after(p_target_person);

    if v_replacement is not null
       and v_replacement <> p_target_person then

      for r in
        select
          id,
          name,
          status
        from public.trash_types
        where next_person = p_target_person
        for update
      loop
        update public.trash_types
        set
          next_person = v_replacement,
          updated_at = now()
        where id = r.id;

        if r.status = 'needs_taking' then
          insert into public.notifications (
            recipient_id,
            type,
            title,
            body,
            trash_id,
            actor_id,
            target_person_id,
            url
          )
          values (
            v_replacement,
            'trash_reassigned',
            '🗑️ ' || r.name || ' needs taking',
            v_target_name
              || ' is away, so it is now your turn to take out '
              || r.name
              || '.',
            r.id,
            v_actor,
            v_replacement,
            '/'
          );
        end if;
      end loop;
    end if;
  end if;

  insert into public.activity_log (
    type,
    actor_id,
    target_person_id,
    summary
  )
  values (
    'vacation',
    v_actor,
    p_target_person,
    coalesce(v_actor_name, 'Someone')
      || ' set '
      || v_target_name
      || ' as '
      || p_availability
      || case
           when p_availability = 'away'
                and p_away_until is not null
           then ' until ' || p_away_until::text
           else ''
         end
  );
end;
$$;


-- =========================================================
-- 10. Function permissions
-- =========================================================

revoke all on function public.register_push_subscription(
  text, text, text, text
) from public, anon;

revoke all on function public.unregister_push_subscription(
  text
) from public, anon;

revoke all on function public.mark_notification_read(
  bigint
) from public, anon;

revoke all on function public.mark_all_notifications_read()
  from public, anon;

grant execute on function public.register_push_subscription(
  text, text, text, text
) to authenticated;

grant execute on function public.unregister_push_subscription(
  text
) to authenticated;

grant execute on function public.mark_notification_read(
  bigint
) to authenticated;

grant execute on function public.mark_all_notifications_read()
  to authenticated;

grant execute on function public.set_trash_status(
  text, text
) to authenticated;

grant execute on function public.set_availability(
  uuid, text, date
) to authenticated;


-- =========================================================
-- 11. Supabase Realtime
-- =========================================================

do $$
begin
  alter publication supabase_realtime
    add table public.notifications;
exception
  when duplicate_object then
    null;
end;
$$;

commit;